USE SQLDrill
GO

CREATE TABLE  PUBLISHER (Name CHAR(30) NOT NULL, 
						Address CHAR(30) NOT NULL, 
						Phone CHAR(15) NULL,
						PRIMARY KEY(Name));
CREATE TABLE  BOOK (BookId INT PRIMARY KEY NOT NULL, 
					Title CHAR(30) NOT NULL, 
					PublisherName CHAR(30) FOREIGN KEY REFERENCES PUBLISHER(Name));
CREATE TABLE  BOOK_AUTHORS (BookID INT FOREIGN KEY REFERENCES BOOK(BookId),
						 AuthorName CHAR(30) NULL);
CREATE TABLE  LIBRARY_BRANCH (BranchId INT PRIMARY KEY NOT NULL, 
						BranchName CHAR(30) NOT NULL, 
						Address CHAR(30) NULL);
CREATE TABLE  BOOK_COPIES (BookId INT FOREIGN KEY REFERENCES BOOK(BookId), 
						BranchId INT FOREIGN KEY REFERENCES LIBRARY_BRANCH(BranchId), 
						No_Of_Copies INT NOT NULL);
CREATE TABLE  BORROWER (CardNo INT PRIMARY KEY NOT NULL, 
						Name CHAR(30) NOT NULL, 
						Address CHAR(30) NULL, 
						Phone CHAR(15) NULL);
CREATE TABLE  BOOK_LOANS (BookId INT FOREIGN KEY REFERENCES BOOK(BookId), 
						BranchId INT FOREIGN KEY REFERENCES LIBRARY_BRANCH(BranchId), 
						CardNo INT FOREIGN KEY REFERENCES BORROWER(CardNo), 
						DateOut DATE NOT NULL, 
						DueDate DATE NOT NULL);




