USE SQLDrill
GO

CREATE TABLE  BOOK (BookId INT PRIMARY KEY NOT NULL, Title CHAR(30) NOT NULL, PublisherName CHAR(30) NULL);
CREATE TABLE  BOOK_AUTHORS (BookID INT PRIMARY KEY NOT NULL, AuthorName CHAR(30) NULL);
CREATE TABLE  PUBLISHER (Name CHAR(30) NOT NULL, Address CHAR(30) NOT NULL, Phone CHAR(15) NULL);
CREATE TABLE  BOOK_COPIES (BookId INT NOT NULL, BranchId INT NOT NULL, No_Of_Copies INT NOT NULL);
CREATE TABLE  BOOK_LOANS (BookId INT NOT NULL, BranchId INT NOT NULL, CardNo INT NOT NULL, DateOut DATE NOT NULL, DueDate DATE NOT NULL);
CREATE TABLE  BORROWER (CardNo INT PRIMARY KEY NOT NULL, Name CHAR(30) NOT NULL, Address CHAR(30) NULL, Phone CHAR(15) NULL);
CREATE TABLE  LIBRARY_BRANCH (BranchId INT PRIMARY KEY NOT NULL, BranchName CHAR(30) NOT NULL, Address CHAR(30) NULL);


